---
version: "3.7"
services:
  lab-res-api:
    build:
      context: .
      args:
        - JAR_FILE=./build/libs/lab-res.jar
    container_name: lab-res
    ports:
      - "8080:8080"
    restart: "always"