openapi: "3.0.3"
info:
  title: lab-res API - Beta
  version: "1"
  description: LabRes provides an API to establish a direct connection between laboratory results and citizens.
  contact:
    name: Healthmetrix GmbH
    url: https://www.labres.de
    email: admin@healthmetrix.com
servers:
  - url: "https://api.labres.dev.healthmetrix.com/{version}"
    description: development environment for the LabRes apiKey
    variables:
      version:
        default: v1
tags:
  - name: External Order Number API
    description: Endpoints to support External Order Numbers (EONs)
  - name: Laboratory API
    description: Endpoints to be invoked by laboratories to report results
components:
  securitySchemes:
    LabCredential:
      type: apiKey
      in: header
      name: Authorization
      description: Base-64 encoded basic auth credential, the username of which is the Client ID used to authorize labs to upload results for an external or internal order number
    OrdersApiToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: validated by JWKS
  schemas:
    GeneralError:
      type: object
      properties:
        message:
          type: string
  responses:
    UnauthorizedApiKeyError:
      description: API key invalid or missing
      headers:
        WWW-Authenticate:
          schema:
            type: string
    GeneralError:
      description: General error response body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
paths:
  /orders:
    post:
      summary: Issues a new globally unique External Order Number (EON). The number of issuing  EONs is limited to 3 per subject.
      description: Should only be invoked for verified users (logged into account or verified email address)
      tags:
        - External Order Number API
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                notificationId:
                  type: string
                  description: Optional notification ID sent from Data4Life that can be used later to notify them that lab results have been uploaded.
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: A unique internal identifier for the order
                    format: UUID
                  externalOrderNumber:
                    type: string
                    format: externalOrderNumber
                    description: numeric 8-digit-long identifier
                example:
                  id: 65e524cb-7494-4073-ad16-495fed0d79e4
                  externalOrderNumber: X72UN3K8
        '401':
          $ref: "#/components/responses/UnauthorizedApiKeyError"
        '500':
          description: Internal server error
          $ref: "#/components/responses/GeneralError"
      security:
        - OrdersApiToken: []
  /orders/{orderId}:
    get:
      summary: returns the current status of a given lab order
      description: Should only be invoked for verified users (logged into account or verified email address)
      tags:
        - External Order Number API
      parameters:
        - name: orderId
          in: path
          description: UUID of an order that has been sent to a lab
          required: true
          schema:
            type: string
            format: uuid
            description: A Version 4 UUID
      responses:
        '200':
          description: returns current status of the lab order
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [POSITIVE, WEAK_POSITIVE, NEGATIVE, INVALID, IN_PROGRESS]
                    description: Status enum to indicate if the lab result is in progress, sample material has been found invalid,  or if it has a positive or negative result
                example:
                  status: POSITIVE
        '401':
          $ref: "#/components/responses/UnauthorizedApiKeyError"
        '404':
          description: no order for the given id found
        '500':
          description: Internal server error
          $ref: "#/components/responses/GeneralError"
      security:
        - OrdersApiToken: []
  /results/{type}:
    put:
      summary: allows for uploading a result of a lab order
      tags:
        - Laboratory API
      parameters:
        - name: type
          in: path
          description: Type of result being uploaded
          required: true
          schema:
            type: string
            enum: [json, ldt, obx]
      requestBody:
        description: Lab result as OBX message, LDT document, or JSON object. Body must include either external or internal order numbers.  In the case of internal, lab ID is taken from authorization headers.
        content:
          'text/plain':
            schema:
              type: string
              format: OBX or LDT
              description: An OBX Segment of an HL7 ORU R1 message (see https://wiki.hl7.de/index.php?title=Segment_OBX for details), or an LDT message
          'application/json':
            schema:
              type: object
              properties:
                result:
                  type: string
                  enum: [ POSITIVE, WEAK_POSITIVE, NEGATIVE, INVALID, IN_PROGRESS ]
                  description: The lab result.
              required:
                - result
      responses:
        '200':
          description: Result uploaded successfully
        '401':
          $ref: "#/components/responses/UnauthorizedApiKeyError"
        '404':
          description: no order for external order number found
        '500':
          description: Internal server error
          $ref: "#/components/responses/GeneralError"
      security:
        - LabCredential: []
