labres:
  stage: local
  registry:
    labs:
      - id: test_lab
        issuers: test_issuer, labres

dynamo:
  table-name: order_information
  local-endpoint: http://localhost:8000

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /docs

documentation-info:
  title: lab-res API - Beta
  version: 1
  description: LabRes provides an API to establish a direct connection between laboratory results and citizens.
  servers:
    - url: http://localhost:8080
      description: local dev environment for LabRes
      version: v1
  contact:
    name: Healthmetrix GmbH
    url: https://www.labres.de
    email: admin@healthmetrix.com

management:
  metrics:
    use-global-registry: false # to prevent spring from adding cloudwatch when starting locally
    export.simple.enabled: true
  endpoints:
    web.exposure.include: health,info,beans,conditions,env,metrics
    health:
      show-details: always
      show-components: always

notification:
  basic-auth:
    user: # empty
    pass: # empty

# has to be a comma separated string
cors-domains: "*"

---
spring:
  profiles: jsonlog
  main.banner-mode: off

---
spring:
  profiles: cloudwatch

management:
  metrics:
    export.simple.enabled: false

metrics:
  cloudwatch:
    stepInSeconds: 30

---
labres:
  stage: dev
  registry:
    labs:
      - id: hmx
        issuers: hmx, labres
      - id: d4l
        issuers: labres

spring:
  profiles: dev
  profiles.include: dynamo, notify, secrets, jsonlog, cloudwatch

dynamo.local-endpoint:

documentation-info:
  servers:
    - url: https://api.dev.labres.de
      description: dev environment for LabRes
      version: v1

management:
  endpoints:
    web.exposure:
      include: info,health

---
labres:
  stage: prod
  registry:
    labs:
      - id: charite
        issuers: labres
      - id: kevb
        issuers: kevb
      - id: hmx
        issuers: hmx

spring:
  profiles: prod
  profiles.include: dynamo, notify, secrets, jsonlog, cloudwatch

metrics:
  cloudwatch:
    stepInSeconds: 3

dynamo.local-endpoint:

documentation-info:
  servers:
    - url: https://api.labres.de
      description: production environment for LabRes
      version: v1

management:
  endpoints:
    web.exposure:
      include: info,health