labres:
  stage: local
  registry:
    labs:
      - id: test_lab
        issuers: test_issuer, labres

dynamo:
  table-name: order_information
  local-endpoint: http://localhost:8000

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /docs

documentation-info:
  title: lab-res API - Beta
  version: 1
  description: LabRes provides an API to establish a direct connection between laboratory results and citizens.
  servers:
    - url: http://localhost:8080
      description: local dev environment for LabRes
      version: v1
  contact:
    name: Healthmetrix GmbH
    url: https://www.labres.de
    email: admin@healthmetrix.com

notification:
  basic-auth:
    user: # empty
    pass: # empty

# has to be a comma separated string
cors-domains: "*"

---
labres:
  stage: dev
  registry:
    labs:
      - id: hmx
        issuers: hmx, labres
      - id: d4l
        issuers: labres

spring:
  profiles: dev
  # TODO: find out why notify doesn't work
  profiles.include: dynamo, notify, secrets

dynamo.local-endpoint:

documentation-info:
  servers:
    - url: https://api.labres.de
      description: production environment for LabRes
      version: v1

---
labres:
  stage: prod
  registry:
    labs:
      - id: charite
        issuers: labres
      - id: kevb
        issuers: kevb

spring:
  profiles: prod
  # TODO: find out why notify doesn't work
  profiles.include: dynamo, notify, secrets, migrate-test-types, migrate-samples

dynamo.local-endpoint:

documentation-info:
  servers:
    - url: https://prod.api.labres.de
      description: production environment for LabRes
      version: v1