dynamo:
  table-name: order_information
  local-endpoint: http://localhost:8000

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /docs

documentation-info:
  title: lab-res API - Beta
  version: 1
  description: LabRes provides an API to establish a direct connection between laboratory results and citizens.
  servers:
    - url: https://api.labres.dev.healthmetrix.com/{version}
      description: development environment for the LabRes apiKey
      version: v1
  contact:
    name: Healthmetrix GmbH
    url: https://www.labres.de
    email: admin@healthmetrix.com

notification:
  basic-auth:
    user: # empty
    pass: # empty

---
spring:
  profiles: dev
  profiles.include: dynamo

dynamo.local-endpoint: